// const rootAPI = 'http://localhost:5000/'
const rootAPI = 'http://54.251.85.88:5000/';
export const FETCH_ALL_EVENT_API = rootAPI + 'all_events';
export const FETCH_EVENT_BY_ID_API = rootAPI + 'get_event_by_id';
export const FETCH_ALL_COMMENT_API = rootAPI + 'fetch_all_ano_comments';
export const ADD_WINFUN_EVENT_API = rootAPI + 'add_event';
export const UPDATE_WINFUN_EVENT_API = rootAPI + 'update_event';
export const UPLOAD_IMAGE = rootAPI + 'upload_image';
export const IMAGE_STORAGE_API = rootAPI + 'image/';
